[2024-11-19T11:42:18.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-19T11:42:18.180+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Loan_Request_Report.Extract __airflow_temporary_run_2024-11-19T11:41:45.397826+00:00__ [queued]>
[2024-11-19T11:42:18.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Loan_Request_Report.Extract __airflow_temporary_run_2024-11-19T11:41:45.397826+00:00__ [queued]>
[2024-11-19T11:42:18.206+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-19T11:42:18.282+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Extract> on 2024-11-11 00:00:00+00:00
[2024-11-19T11:42:18.311+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=388) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-19T11:42:18.320+0000] {standard_task_runner.py:64} INFO - Started process 396 to run task
[2024-11-19T11:42:18.333+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Loan_Request_Report', 'Extract', '__***_temporary_run_2024-11-19T11:41:45.397826+00:00__', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/dagLoanRequest.py', '--cfg-path', '/tmp/tmpcrovjw29']
[2024-11-19T11:42:18.343+0000] {standard_task_runner.py:91} INFO - Job 303: Subtask Extract
[2024-11-19T11:42:18.586+0000] {task_command.py:426} INFO - Running <TaskInstance: Loan_Request_Report.Extract __airflow_temporary_run_2024-11-19T11:41:45.397826+00:00__ [running]> on host 2bac939b7bc7
[2024-11-19T11:42:19.196+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Loan_Request_Report' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2024-11-19T11:41:45.397826+00:00__'
[2024-11-19T11:42:19.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-19T11:42:20.208+0000] {hive.py:475} INFO - USE `m2t`
[2024-11-19T11:42:24.020+0000] {warnings.py:112} WARNING - /opt/***/dags/etlProcess.py:150: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query1, conn)

[2024-11-19T11:42:24.021+0000] {hive.py:475} INFO - 
        SELECT
            cl.id as id1,
            lr.id as id2,
            cl.phone_number AS N_GSM,
            cl.first_name  AS NOM,
            cl.last_name AS PRENOM,
            cl.age as age,
            cl.city_label as city,
            cl.gender as gender,
            lr.code_ls AS CODE_DOSSIER,
            lr.requested_amount AS MONTANT_DEMANDE,
            lr.awarded_amount AS MONTANT_ACCORDE,
            lr.created_date AS DATE_DEMANDE_CREDIT,
            SPLIT(lr.created_date, ' ')[1] AS HEURE_DEMANDE_CREDIT,
            lr.status AS STATUT_DOSSIER,
            lr.rejection_reason as rejection_reason,
            lr.requested_deadlines as NOMBRE_ECHEANCE,
            deadlines.deadline1 AS DATE_ECHEANCE1,
            deadlines.deadline2 AS DATE_ECHEANCE2,
            deadlines.deadline3 AS DATE_ECHEANCE3,
            deadlines.deadline4 AS DATE_ECHEANCE4,
            lr.fees AS FREE_DE_SERVICE,
            lr.rate AS TAUX_D_INTERET,
            CASE
                WHEN lr.code_es = '123456' THEN '012006'
                ELSE lr.code_es
            END AS CODE_AGENCE
        FROM clients cl
        LEFT JOIN loan_request lr ON cl.id = lr.fk_client
        LEFT JOIN (
            SELECT 
                fk_loan_request AS loan_request_id, 
                MAX(CASE WHEN deadline_row = 1 THEN deadline END) AS deadline1,
                MAX(CASE WHEN deadline_row = 2 THEN deadline END) AS deadline2,
                MAX(CASE WHEN deadline_row = 3 THEN deadline END) AS deadline3,
                MAX(CASE WHEN deadline_row = 4 THEN deadline END) AS deadline4
            FROM (
                SELECT 
                    fk_loan_request, 
                    deadline, 
                    ROW_NUMBER() OVER (PARTITION BY fk_loan_request ORDER BY deadline) AS deadline_row
                FROM payment_deadline
            ) deadline_subquery
            GROUP BY fk_loan_request
        ) AS deadlines ON lr.id = deadlines.loan_request_id
        WHERE lr.produit = 'TAYSSIR' AND date(lr.created_date) >= '2024-06-13'
        ORDER BY DATE_DEMANDE_CREDIT DESC
    
[2024-11-19T11:45:25.425+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 213, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 261, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1821, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 510, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1807, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-19T11:45:25.713+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-19T11:46:01.077+0000] {warnings.py:112} WARNING - /opt/***/dags/etlProcess.py:168: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(query2, conn)

[2024-11-19T11:46:01.086+0000] {hive.py:475} INFO - 
        SELECT
            cl.id as id3,
            lr.id as id4,
            lr.code_es as code_es,
            lr.produit as produit,
            pd.method as method,
            pd.deadline as deadline,
            pd.payment_date as payment_date,
            pd.status as status
        FROM clients cl
        LEFT JOIN loan_request lr ON cl.id = lr.fk_client
        LEFT JOIN payment_deadline pd ON lr.id = pd.fk_loan_request
        WHERE lr.produit = 'TAYSSIR' AND date(lr.created_date) >= '2024-06-13'
    
[2024-11-19T11:46:41.299+0000] {logging_mixin.py:188} INFO -                                      id1  ...              status
53  dbadc4c8-2390-4b95-a9b0-1be2c9ffbf45  ...                None
54  59e720aa-296c-4d66-b334-dbcc8fc65180  ...              UNPAID
57  dbadc4c8-2390-4b95-a9b0-1be2c9ffbf45  ...              UNPAID
56  dbadc4c8-2390-4b95-a9b0-1be2c9ffbf45  ...                None
55  64ab25ae-c510-4ca4-b710-e1fedafccdc3  ...              UNPAID
52  64ab25ae-c510-4ca4-b710-e1fedafccdc3  ...                None
51  393da9a8-fc25-40a7-9926-265de088681b  ...                None
50  393da9a8-fc25-40a7-9926-265de088681b  ...                None
2   393da9a8-fc25-40a7-9926-265de088681b  ...                None
1   393da9a8-fc25-40a7-9926-265de088681b  ...                None
49  393da9a8-fc25-40a7-9926-265de088681b  ...                None
48  393da9a8-fc25-40a7-9926-265de088681b  ...                None
47  70d01bc9-273d-465e-b286-eeac79bb7143  ...  PAID_LS_RECONCILED
46  70d01bc9-273d-465e-b286-eeac79bb7143  ...              UNPAID
45  70d01bc9-273d-465e-b286-eeac79bb7143  ...              UNPAID
44  70d01bc9-273d-465e-b286-eeac79bb7143  ...                None
25  70d01bc9-273d-465e-b286-eeac79bb7143  ...                None
8   70d01bc9-273d-465e-b286-eeac79bb7143  ...                None
6   393da9a8-fc25-40a7-9926-265de088681b  ...                None
19  393da9a8-fc25-40a7-9926-265de088681b  ...                None
5   e8497611-00d5-407c-9d81-0292a0066ed9  ...                None
38  e8497611-00d5-407c-9d81-0292a0066ed9  ...                None
31  e8497611-00d5-407c-9d81-0292a0066ed9  ...                None
30  e8497611-00d5-407c-9d81-0292a0066ed9  ...                None
18  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...             PAID_LS
17  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
16  0d9717ae-43ce-435b-b43f-9762ff4c2c42  ...                None
33  0d9717ae-43ce-435b-b43f-9762ff4c2c42  ...                None
29  0d9717ae-43ce-435b-b43f-9762ff4c2c42  ...                None
43  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
22  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
26  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
11  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
24  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
12  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
35  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
36  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
37  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
23  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
39  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
15  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
42  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...                None
21  88f437b6-14c3-47a7-9087-e92f15d69d6c  ...                None
14  fcdd5851-b92f-4003-b54e-1118e78ab519  ...                None
41  fcdd5851-b92f-4003-b54e-1118e78ab519  ...                None
27  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...             PAID_LS
20  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
13  e8497611-00d5-407c-9d81-0292a0066ed9  ...                None
10  3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
9   3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
7   3c0e57f6-e054-47b6-9e26-daad734d2eca  ...              UNPAID
4   6a419a09-6902-45d1-bab4-03cb8d1f7d20  ...                None
3   6a419a09-6902-45d1-bab4-03cb8d1f7d20  ...                None
0   1d4cc8f7-f65b-4d68-b427-1e0c31c45b7a  ...                None
40  ed7bf3ee-e5d9-41ec-af90-7f44835f86aa  ...                None
34  95686f45-71d3-4c23-b0fa-e92aeb18155f  ...                None
32  95686f45-71d3-4c23-b0fa-e92aeb18155f  ...                None
28  e8497611-00d5-407c-9d81-0292a0066ed9  ...                None

[58 rows x 31 columns]
[2024-11-19T11:46:41.346+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-19T11:46:41.349+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-19T11:46:41.416+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Loan_Request_Report, task_id=Extract, run_id=__***_temporary_run_2024-11-19T11:41:45.397826+00:00__, execution_date=20241111T000000, start_date=20241119T114218, end_date=20241119T114641
[2024-11-19T11:46:41.612+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-19T11:46:41.748+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-19T11:46:41.752+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
